"""add title_indicators table

Revision ID: ed7b2c644770
Revises: 53dcabbf19aa
Create Date: 2025-11-17 18:59:43.955052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7b2c644770'
down_revision: Union[str, Sequence[str], None] = '53dcabbf19aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=16), nullable=False),
    sa.Column('title_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_indicators')
    # ### end Alembic commands ###
